apiVersion: v1
kind: Service
metadata:
  name: Boilerplate.WebApi
  labels:
    app: Boilerplate.WebApi
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: Boilerplate.WebApi